language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: npm release
      script: echo "deploy package to npm ..."
      deploy:
        provider: npm
        tag: beta
        email: "sun1993hlj@hotmail.com"
        api_key: $NODE_TOKEN
        skip_cleanup: true
        on:
          branch: dev
cache:
  directories:
    - "node_modules"